#ifndef INCLUDED_CYFITTER_H
#define INCLUDED_CYFITTER_H
#include <cydevice.h>
#include <cydevice_trm.h>

/* ResistiveTouch_1_ADC_SAR_ADC_SAR */
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CLK CYREG_SAR1_CLK
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR0 CYREG_SAR1_CSR0
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR1 CYREG_SAR1_CSR1
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR2 CYREG_SAR1_CSR2
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR3 CYREG_SAR1_CSR3
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR4 CYREG_SAR1_CSR4
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR5 CYREG_SAR1_CSR5
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__CSR6 CYREG_SAR1_CSR6
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__PM_ACT_CFG CYREG_PM_ACT_CFG11
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__PM_ACT_MSK 0x02u
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__PM_STBY_CFG CYREG_PM_STBY_CFG11
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__PM_STBY_MSK 0x02u
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__SW0 CYREG_SAR1_SW0
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__SW2 CYREG_SAR1_SW2
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__SW3 CYREG_SAR1_SW3
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__SW4 CYREG_SAR1_SW4
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__SW6 CYREG_SAR1_SW6
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__TR0 CYREG_SAR1_TR0
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__WRK0 CYREG_SAR1_WRK0
#define ResistiveTouch_1_ADC_SAR_ADC_SAR__WRK1 CYREG_SAR1_WRK1

/* ResistiveTouch_1_ADC_SAR_theACLK */
#define ResistiveTouch_1_ADC_SAR_theACLK__CFG0 CYREG_CLKDIST_ACFG0_CFG0
#define ResistiveTouch_1_ADC_SAR_theACLK__CFG1 CYREG_CLKDIST_ACFG0_CFG1
#define ResistiveTouch_1_ADC_SAR_theACLK__CFG2 CYREG_CLKDIST_ACFG0_CFG2
#define ResistiveTouch_1_ADC_SAR_theACLK__CFG2_SRC_SEL_MASK 0x07u
#define ResistiveTouch_1_ADC_SAR_theACLK__CFG3 CYREG_CLKDIST_ACFG0_CFG3
#define ResistiveTouch_1_ADC_SAR_theACLK__CFG3_PHASE_DLY_MASK 0x0Fu
#define ResistiveTouch_1_ADC_SAR_theACLK__INDEX 0x00u
#define ResistiveTouch_1_ADC_SAR_theACLK__PM_ACT_CFG CYREG_PM_ACT_CFG1
#define ResistiveTouch_1_ADC_SAR_theACLK__PM_ACT_MSK 0x01u
#define ResistiveTouch_1_ADC_SAR_theACLK__PM_STBY_CFG CYREG_PM_STBY_CFG1
#define ResistiveTouch_1_ADC_SAR_theACLK__PM_STBY_MSK 0x01u

/* ResistiveTouch_1_ADC_SAR_IRQ */
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_MASK 0x01u
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_NUMBER 0u
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_PRIOR_NUM 7u
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_0
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ResistiveTouch_1_ADC_SAR_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Clipping_Sense_ctComp */
#define Clipping_Sense_ctComp__CLK CYREG_CMP0_CLK
#define Clipping_Sense_ctComp__CMP_MASK 0x01u
#define Clipping_Sense_ctComp__CMP_NUMBER 0u
#define Clipping_Sense_ctComp__CR CYREG_CMP0_CR
#define Clipping_Sense_ctComp__LUT__CR CYREG_LUT0_CR
#define Clipping_Sense_ctComp__LUT__MSK CYREG_LUT_MSK
#define Clipping_Sense_ctComp__LUT__MSK_MASK 0x01u
#define Clipping_Sense_ctComp__LUT__MSK_SHIFT 0
#define Clipping_Sense_ctComp__LUT__MX CYREG_LUT0_MX
#define Clipping_Sense_ctComp__LUT__SR CYREG_LUT_SR
#define Clipping_Sense_ctComp__LUT__SR_MASK 0x01u
#define Clipping_Sense_ctComp__LUT__SR_SHIFT 0
#define Clipping_Sense_ctComp__PM_ACT_CFG CYREG_PM_ACT_CFG7
#define Clipping_Sense_ctComp__PM_ACT_MSK 0x01u
#define Clipping_Sense_ctComp__PM_STBY_CFG CYREG_PM_STBY_CFG7
#define Clipping_Sense_ctComp__PM_STBY_MSK 0x01u
#define Clipping_Sense_ctComp__SW0 CYREG_CMP0_SW0
#define Clipping_Sense_ctComp__SW2 CYREG_CMP0_SW2
#define Clipping_Sense_ctComp__SW3 CYREG_CMP0_SW3
#define Clipping_Sense_ctComp__SW4 CYREG_CMP0_SW4
#define Clipping_Sense_ctComp__SW6 CYREG_CMP0_SW6
#define Clipping_Sense_ctComp__TR0 CYREG_CMP0_TR0
#define Clipping_Sense_ctComp__TR1 CYREG_CMP0_TR1
#define Clipping_Sense_ctComp__TRIM__TR0 CYREG_FLSHID_MFG_CFG_CMP0_TR0
#define Clipping_Sense_ctComp__TRIM__TR0_HS CYREG_FLSHID_CUST_TABLES_CMP0_TR0_HS
#define Clipping_Sense_ctComp__TRIM__TR1 CYREG_FLSHID_MFG_CFG_CMP0_TR1
#define Clipping_Sense_ctComp__TRIM__TR1_HS CYREG_FLSHID_CUST_TABLES_CMP0_TR1_HS
#define Clipping_Sense_ctComp__WRK CYREG_CMP_WRK
#define Clipping_Sense_ctComp__WRK_MASK 0x01u
#define Clipping_Sense_ctComp__WRK_SHIFT 0

/* LCD_LCD_SPI_IntClock */
#define LCD_LCD_SPI_IntClock__CFG0 CYREG_CLKDIST_DCFG3_CFG0
#define LCD_LCD_SPI_IntClock__CFG1 CYREG_CLKDIST_DCFG3_CFG1
#define LCD_LCD_SPI_IntClock__CFG2 CYREG_CLKDIST_DCFG3_CFG2
#define LCD_LCD_SPI_IntClock__CFG2_SRC_SEL_MASK 0x07u
#define LCD_LCD_SPI_IntClock__INDEX 0x03u
#define LCD_LCD_SPI_IntClock__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define LCD_LCD_SPI_IntClock__PM_ACT_MSK 0x08u
#define LCD_LCD_SPI_IntClock__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define LCD_LCD_SPI_IntClock__PM_STBY_MSK 0x08u

/* ResistiveTouch_1_xm */
#define ResistiveTouch_1_xm__0__MASK 0x01u
#define ResistiveTouch_1_xm__0__PC CYREG_PRT5_PC0
#define ResistiveTouch_1_xm__0__PORT 5u
#define ResistiveTouch_1_xm__0__SHIFT 0
#define ResistiveTouch_1_xm__AG CYREG_PRT5_AG
#define ResistiveTouch_1_xm__AMUX CYREG_PRT5_AMUX
#define ResistiveTouch_1_xm__BIE CYREG_PRT5_BIE
#define ResistiveTouch_1_xm__BIT_MASK CYREG_PRT5_BIT_MASK
#define ResistiveTouch_1_xm__BYP CYREG_PRT5_BYP
#define ResistiveTouch_1_xm__CTL CYREG_PRT5_CTL
#define ResistiveTouch_1_xm__DM0 CYREG_PRT5_DM0
#define ResistiveTouch_1_xm__DM1 CYREG_PRT5_DM1
#define ResistiveTouch_1_xm__DM2 CYREG_PRT5_DM2
#define ResistiveTouch_1_xm__DR CYREG_PRT5_DR
#define ResistiveTouch_1_xm__INP_DIS CYREG_PRT5_INP_DIS
#define ResistiveTouch_1_xm__LCD_COM_SEG CYREG_PRT5_LCD_COM_SEG
#define ResistiveTouch_1_xm__LCD_EN CYREG_PRT5_LCD_EN
#define ResistiveTouch_1_xm__MASK 0x01u
#define ResistiveTouch_1_xm__PORT 5u
#define ResistiveTouch_1_xm__PRT CYREG_PRT5_PRT
#define ResistiveTouch_1_xm__PRTDSI__CAPS_SEL CYREG_PRT5_CAPS_SEL
#define ResistiveTouch_1_xm__PRTDSI__DBL_SYNC_IN CYREG_PRT5_DBL_SYNC_IN
#define ResistiveTouch_1_xm__PRTDSI__OE_SEL0 CYREG_PRT5_OE_SEL0
#define ResistiveTouch_1_xm__PRTDSI__OE_SEL1 CYREG_PRT5_OE_SEL1
#define ResistiveTouch_1_xm__PRTDSI__OUT_SEL0 CYREG_PRT5_OUT_SEL0
#define ResistiveTouch_1_xm__PRTDSI__OUT_SEL1 CYREG_PRT5_OUT_SEL1
#define ResistiveTouch_1_xm__PRTDSI__SYNC_OUT CYREG_PRT5_SYNC_OUT
#define ResistiveTouch_1_xm__PS CYREG_PRT5_PS
#define ResistiveTouch_1_xm__SHIFT 0
#define ResistiveTouch_1_xm__SLW CYREG_PRT5_SLW

/* ResistiveTouch_1_xp */
#define ResistiveTouch_1_xp__0__MASK 0x02u
#define ResistiveTouch_1_xp__0__PC CYREG_PRT5_PC1
#define ResistiveTouch_1_xp__0__PORT 5u
#define ResistiveTouch_1_xp__0__SHIFT 1
#define ResistiveTouch_1_xp__AG CYREG_PRT5_AG
#define ResistiveTouch_1_xp__AMUX CYREG_PRT5_AMUX
#define ResistiveTouch_1_xp__BIE CYREG_PRT5_BIE
#define ResistiveTouch_1_xp__BIT_MASK CYREG_PRT5_BIT_MASK
#define ResistiveTouch_1_xp__BYP CYREG_PRT5_BYP
#define ResistiveTouch_1_xp__CTL CYREG_PRT5_CTL
#define ResistiveTouch_1_xp__DM0 CYREG_PRT5_DM0
#define ResistiveTouch_1_xp__DM1 CYREG_PRT5_DM1
#define ResistiveTouch_1_xp__DM2 CYREG_PRT5_DM2
#define ResistiveTouch_1_xp__DR CYREG_PRT5_DR
#define ResistiveTouch_1_xp__INP_DIS CYREG_PRT5_INP_DIS
#define ResistiveTouch_1_xp__LCD_COM_SEG CYREG_PRT5_LCD_COM_SEG
#define ResistiveTouch_1_xp__LCD_EN CYREG_PRT5_LCD_EN
#define ResistiveTouch_1_xp__MASK 0x02u
#define ResistiveTouch_1_xp__PORT 5u
#define ResistiveTouch_1_xp__PRT CYREG_PRT5_PRT
#define ResistiveTouch_1_xp__PRTDSI__CAPS_SEL CYREG_PRT5_CAPS_SEL
#define ResistiveTouch_1_xp__PRTDSI__DBL_SYNC_IN CYREG_PRT5_DBL_SYNC_IN
#define ResistiveTouch_1_xp__PRTDSI__OE_SEL0 CYREG_PRT5_OE_SEL0
#define ResistiveTouch_1_xp__PRTDSI__OE_SEL1 CYREG_PRT5_OE_SEL1
#define ResistiveTouch_1_xp__PRTDSI__OUT_SEL0 CYREG_PRT5_OUT_SEL0
#define ResistiveTouch_1_xp__PRTDSI__OUT_SEL1 CYREG_PRT5_OUT_SEL1
#define ResistiveTouch_1_xp__PRTDSI__SYNC_OUT CYREG_PRT5_SYNC_OUT
#define ResistiveTouch_1_xp__PS CYREG_PRT5_PS
#define ResistiveTouch_1_xp__SHIFT 1
#define ResistiveTouch_1_xp__SLW CYREG_PRT5_SLW

/* ResistiveTouch_1_ym */
#define ResistiveTouch_1_ym__0__MASK 0x04u
#define ResistiveTouch_1_ym__0__PC CYREG_PRT5_PC2
#define ResistiveTouch_1_ym__0__PORT 5u
#define ResistiveTouch_1_ym__0__SHIFT 2
#define ResistiveTouch_1_ym__AG CYREG_PRT5_AG
#define ResistiveTouch_1_ym__AMUX CYREG_PRT5_AMUX
#define ResistiveTouch_1_ym__BIE CYREG_PRT5_BIE
#define ResistiveTouch_1_ym__BIT_MASK CYREG_PRT5_BIT_MASK
#define ResistiveTouch_1_ym__BYP CYREG_PRT5_BYP
#define ResistiveTouch_1_ym__CTL CYREG_PRT5_CTL
#define ResistiveTouch_1_ym__DM0 CYREG_PRT5_DM0
#define ResistiveTouch_1_ym__DM1 CYREG_PRT5_DM1
#define ResistiveTouch_1_ym__DM2 CYREG_PRT5_DM2
#define ResistiveTouch_1_ym__DR CYREG_PRT5_DR
#define ResistiveTouch_1_ym__INP_DIS CYREG_PRT5_INP_DIS
#define ResistiveTouch_1_ym__LCD_COM_SEG CYREG_PRT5_LCD_COM_SEG
#define ResistiveTouch_1_ym__LCD_EN CYREG_PRT5_LCD_EN
#define ResistiveTouch_1_ym__MASK 0x04u
#define ResistiveTouch_1_ym__PORT 5u
#define ResistiveTouch_1_ym__PRT CYREG_PRT5_PRT
#define ResistiveTouch_1_ym__PRTDSI__CAPS_SEL CYREG_PRT5_CAPS_SEL
#define ResistiveTouch_1_ym__PRTDSI__DBL_SYNC_IN CYREG_PRT5_DBL_SYNC_IN
#define ResistiveTouch_1_ym__PRTDSI__OE_SEL0 CYREG_PRT5_OE_SEL0
#define ResistiveTouch_1_ym__PRTDSI__OE_SEL1 CYREG_PRT5_OE_SEL1
#define ResistiveTouch_1_ym__PRTDSI__OUT_SEL0 CYREG_PRT5_OUT_SEL0
#define ResistiveTouch_1_ym__PRTDSI__OUT_SEL1 CYREG_PRT5_OUT_SEL1
#define ResistiveTouch_1_ym__PRTDSI__SYNC_OUT CYREG_PRT5_SYNC_OUT
#define ResistiveTouch_1_ym__PS CYREG_PRT5_PS
#define ResistiveTouch_1_ym__SHIFT 2
#define ResistiveTouch_1_ym__SLW CYREG_PRT5_SLW

/* ResistiveTouch_1_yp */
#define ResistiveTouch_1_yp__0__MASK 0x08u
#define ResistiveTouch_1_yp__0__PC CYREG_PRT5_PC3
#define ResistiveTouch_1_yp__0__PORT 5u
#define ResistiveTouch_1_yp__0__SHIFT 3
#define ResistiveTouch_1_yp__AG CYREG_PRT5_AG
#define ResistiveTouch_1_yp__AMUX CYREG_PRT5_AMUX
#define ResistiveTouch_1_yp__BIE CYREG_PRT5_BIE
#define ResistiveTouch_1_yp__BIT_MASK CYREG_PRT5_BIT_MASK
#define ResistiveTouch_1_yp__BYP CYREG_PRT5_BYP
#define ResistiveTouch_1_yp__CTL CYREG_PRT5_CTL
#define ResistiveTouch_1_yp__DM0 CYREG_PRT5_DM0
#define ResistiveTouch_1_yp__DM1 CYREG_PRT5_DM1
#define ResistiveTouch_1_yp__DM2 CYREG_PRT5_DM2
#define ResistiveTouch_1_yp__DR CYREG_PRT5_DR
#define ResistiveTouch_1_yp__INP_DIS CYREG_PRT5_INP_DIS
#define ResistiveTouch_1_yp__LCD_COM_SEG CYREG_PRT5_LCD_COM_SEG
#define ResistiveTouch_1_yp__LCD_EN CYREG_PRT5_LCD_EN
#define ResistiveTouch_1_yp__MASK 0x08u
#define ResistiveTouch_1_yp__PORT 5u
#define ResistiveTouch_1_yp__PRT CYREG_PRT5_PRT
#define ResistiveTouch_1_yp__PRTDSI__CAPS_SEL CYREG_PRT5_CAPS_SEL
#define ResistiveTouch_1_yp__PRTDSI__DBL_SYNC_IN CYREG_PRT5_DBL_SYNC_IN
#define ResistiveTouch_1_yp__PRTDSI__OE_SEL0 CYREG_PRT5_OE_SEL0
#define ResistiveTouch_1_yp__PRTDSI__OE_SEL1 CYREG_PRT5_OE_SEL1
#define ResistiveTouch_1_yp__PRTDSI__OUT_SEL0 CYREG_PRT5_OUT_SEL0
#define ResistiveTouch_1_yp__PRTDSI__OUT_SEL1 CYREG_PRT5_OUT_SEL1
#define ResistiveTouch_1_yp__PRTDSI__SYNC_OUT CYREG_PRT5_SYNC_OUT
#define ResistiveTouch_1_yp__PS CYREG_PRT5_PS
#define ResistiveTouch_1_yp__SHIFT 3
#define ResistiveTouch_1_yp__SLW CYREG_PRT5_SLW

/* LCD_LCD_SPI_BSPIM */
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__16BIT_STATUS_AUX_CTL_REG CYREG_B1_UDB06_07_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__16BIT_STATUS_REG CYREG_B1_UDB06_07_ST
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__MASK_REG CYREG_B1_UDB06_MSK
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__MASK_ST_AUX_CTL_REG CYREG_B1_UDB06_MSK_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__PER_ST_AUX_CTL_REG CYREG_B1_UDB06_MSK_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__STATUS_AUX_CTL_REG CYREG_B1_UDB06_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__STATUS_CNT_REG CYREG_B1_UDB06_ST_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__STATUS_CONTROL_REG CYREG_B1_UDB06_ST_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter_ST__STATUS_REG CYREG_B1_UDB06_ST
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_CONTROL_AUX_CTL_REG CYREG_B1_UDB06_07_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_CONTROL_CONTROL_REG CYREG_B1_UDB06_07_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_CONTROL_COUNT_REG CYREG_B1_UDB06_07_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_COUNT_CONTROL_REG CYREG_B1_UDB06_07_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_COUNT_COUNT_REG CYREG_B1_UDB06_07_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_MASK_MASK_REG CYREG_B1_UDB06_07_MSK
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_MASK_PERIOD_REG CYREG_B1_UDB06_07_MSK
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_PERIOD_MASK_REG CYREG_B1_UDB06_07_MSK
#define LCD_LCD_SPI_BSPIM_BitCounter__16BIT_PERIOD_PERIOD_REG CYREG_B1_UDB06_07_MSK
#define LCD_LCD_SPI_BSPIM_BitCounter__CONTROL_AUX_CTL_REG CYREG_B1_UDB06_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter__CONTROL_REG CYREG_B1_UDB06_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__CONTROL_ST_REG CYREG_B1_UDB06_ST_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__COUNT_REG CYREG_B1_UDB06_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__COUNT_ST_REG CYREG_B1_UDB06_ST_CTL
#define LCD_LCD_SPI_BSPIM_BitCounter__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB06_MSK_ACTL
#define LCD_LCD_SPI_BSPIM_BitCounter__PERIOD_REG CYREG_B1_UDB06_MSK
#define LCD_LCD_SPI_BSPIM_BitCounter__PER_CTL_AUX_CTL_REG CYREG_B1_UDB06_MSK_ACTL
#define LCD_LCD_SPI_BSPIM_RxStsReg__16BIT_STATUS_AUX_CTL_REG CYREG_B1_UDB07_08_ACTL
#define LCD_LCD_SPI_BSPIM_RxStsReg__16BIT_STATUS_REG CYREG_B1_UDB07_08_ST
#define LCD_LCD_SPI_BSPIM_RxStsReg__4__MASK 0x10u
#define LCD_LCD_SPI_BSPIM_RxStsReg__4__POS 4
#define LCD_LCD_SPI_BSPIM_RxStsReg__5__MASK 0x20u
#define LCD_LCD_SPI_BSPIM_RxStsReg__5__POS 5
#define LCD_LCD_SPI_BSPIM_RxStsReg__6__MASK 0x40u
#define LCD_LCD_SPI_BSPIM_RxStsReg__6__POS 6
#define LCD_LCD_SPI_BSPIM_RxStsReg__MASK 0x70u
#define LCD_LCD_SPI_BSPIM_RxStsReg__MASK_REG CYREG_B1_UDB07_MSK
#define LCD_LCD_SPI_BSPIM_RxStsReg__STATUS_AUX_CTL_REG CYREG_B1_UDB07_ACTL
#define LCD_LCD_SPI_BSPIM_RxStsReg__STATUS_REG CYREG_B1_UDB07_ST
#define LCD_LCD_SPI_BSPIM_TxStsReg__0__MASK 0x01u
#define LCD_LCD_SPI_BSPIM_TxStsReg__0__POS 0
#define LCD_LCD_SPI_BSPIM_TxStsReg__16BIT_STATUS_AUX_CTL_REG CYREG_B0_UDB07_08_ACTL
#define LCD_LCD_SPI_BSPIM_TxStsReg__16BIT_STATUS_REG CYREG_B0_UDB07_08_ST
#define LCD_LCD_SPI_BSPIM_TxStsReg__1__MASK 0x02u
#define LCD_LCD_SPI_BSPIM_TxStsReg__1__POS 1
#define LCD_LCD_SPI_BSPIM_TxStsReg__2__MASK 0x04u
#define LCD_LCD_SPI_BSPIM_TxStsReg__2__POS 2
#define LCD_LCD_SPI_BSPIM_TxStsReg__3__MASK 0x08u
#define LCD_LCD_SPI_BSPIM_TxStsReg__3__POS 3
#define LCD_LCD_SPI_BSPIM_TxStsReg__4__MASK 0x10u
#define LCD_LCD_SPI_BSPIM_TxStsReg__4__POS 4
#define LCD_LCD_SPI_BSPIM_TxStsReg__MASK 0x1Fu
#define LCD_LCD_SPI_BSPIM_TxStsReg__MASK_REG CYREG_B0_UDB07_MSK
#define LCD_LCD_SPI_BSPIM_TxStsReg__STATUS_AUX_CTL_REG CYREG_B0_UDB07_ACTL
#define LCD_LCD_SPI_BSPIM_TxStsReg__STATUS_REG CYREG_B0_UDB07_ST
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_A0_REG CYREG_B1_UDB07_08_A0
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_A1_REG CYREG_B1_UDB07_08_A1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_D0_REG CYREG_B1_UDB07_08_D0
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_D1_REG CYREG_B1_UDB07_08_D1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_DP_AUX_CTL_REG CYREG_B1_UDB07_08_ACTL
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_F0_REG CYREG_B1_UDB07_08_F0
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__16BIT_F1_REG CYREG_B1_UDB07_08_F1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__A0_A1_REG CYREG_B1_UDB07_A0_A1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__A0_REG CYREG_B1_UDB07_A0
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__A1_REG CYREG_B1_UDB07_A1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__D0_D1_REG CYREG_B1_UDB07_D0_D1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__D0_REG CYREG_B1_UDB07_D0
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__D1_REG CYREG_B1_UDB07_D1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__DP_AUX_CTL_REG CYREG_B1_UDB07_ACTL
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__F0_F1_REG CYREG_B1_UDB07_F0_F1
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__F0_REG CYREG_B1_UDB07_F0
#define LCD_LCD_SPI_BSPIM_sR8_Dp_u0__F1_REG CYREG_B1_UDB07_F1

/* drive_freq_range */
#define drive_freq_range__0__MASK 0x08u
#define drive_freq_range__0__PC CYREG_PRT3_PC3
#define drive_freq_range__0__PORT 3u
#define drive_freq_range__0__SHIFT 3
#define drive_freq_range__AG CYREG_PRT3_AG
#define drive_freq_range__AMUX CYREG_PRT3_AMUX
#define drive_freq_range__BIE CYREG_PRT3_BIE
#define drive_freq_range__BIT_MASK CYREG_PRT3_BIT_MASK
#define drive_freq_range__BYP CYREG_PRT3_BYP
#define drive_freq_range__CTL CYREG_PRT3_CTL
#define drive_freq_range__DM0 CYREG_PRT3_DM0
#define drive_freq_range__DM1 CYREG_PRT3_DM1
#define drive_freq_range__DM2 CYREG_PRT3_DM2
#define drive_freq_range__DR CYREG_PRT3_DR
#define drive_freq_range__INP_DIS CYREG_PRT3_INP_DIS
#define drive_freq_range__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define drive_freq_range__LCD_EN CYREG_PRT3_LCD_EN
#define drive_freq_range__MASK 0x08u
#define drive_freq_range__PORT 3u
#define drive_freq_range__PRT CYREG_PRT3_PRT
#define drive_freq_range__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define drive_freq_range__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define drive_freq_range__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define drive_freq_range__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define drive_freq_range__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define drive_freq_range__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define drive_freq_range__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define drive_freq_range__PS CYREG_PRT3_PS
#define drive_freq_range__SHIFT 3
#define drive_freq_range__SLW CYREG_PRT3_SLW

/* LCD_LCD_Control */
#define LCD_LCD_Control_Sync_ctrl_reg__0__MASK 0x01u
#define LCD_LCD_Control_Sync_ctrl_reg__0__POS 0
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB04_05_ACTL
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB04_05_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB04_05_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB04_05_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB04_05_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB04_05_MSK
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB04_05_MSK
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB04_05_MSK
#define LCD_LCD_Control_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB04_05_MSK
#define LCD_LCD_Control_Sync_ctrl_reg__1__MASK 0x02u
#define LCD_LCD_Control_Sync_ctrl_reg__1__POS 1
#define LCD_LCD_Control_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB04_ACTL
#define LCD_LCD_Control_Sync_ctrl_reg__CONTROL_REG CYREG_B0_UDB04_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB04_ST_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__COUNT_REG CYREG_B0_UDB04_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB04_ST_CTL
#define LCD_LCD_Control_Sync_ctrl_reg__MASK 0x03u
#define LCD_LCD_Control_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB04_MSK_ACTL
#define LCD_LCD_Control_Sync_ctrl_reg__PERIOD_REG CYREG_B0_UDB04_MSK
#define LCD_LCD_Control_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB04_MSK_ACTL

/* ADC_Bypass_P32 */
#define ADC_Bypass_P32__0__MASK 0x04u
#define ADC_Bypass_P32__0__PC CYREG_PRT3_PC2
#define ADC_Bypass_P32__0__PORT 3u
#define ADC_Bypass_P32__0__SHIFT 2
#define ADC_Bypass_P32__AG CYREG_PRT3_AG
#define ADC_Bypass_P32__AMUX CYREG_PRT3_AMUX
#define ADC_Bypass_P32__BIE CYREG_PRT3_BIE
#define ADC_Bypass_P32__BIT_MASK CYREG_PRT3_BIT_MASK
#define ADC_Bypass_P32__BYP CYREG_PRT3_BYP
#define ADC_Bypass_P32__CTL CYREG_PRT3_CTL
#define ADC_Bypass_P32__DM0 CYREG_PRT3_DM0
#define ADC_Bypass_P32__DM1 CYREG_PRT3_DM1
#define ADC_Bypass_P32__DM2 CYREG_PRT3_DM2
#define ADC_Bypass_P32__DR CYREG_PRT3_DR
#define ADC_Bypass_P32__INP_DIS CYREG_PRT3_INP_DIS
#define ADC_Bypass_P32__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define ADC_Bypass_P32__LCD_EN CYREG_PRT3_LCD_EN
#define ADC_Bypass_P32__MASK 0x04u
#define ADC_Bypass_P32__PORT 3u
#define ADC_Bypass_P32__PRT CYREG_PRT3_PRT
#define ADC_Bypass_P32__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define ADC_Bypass_P32__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define ADC_Bypass_P32__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define ADC_Bypass_P32__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define ADC_Bypass_P32__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define ADC_Bypass_P32__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define ADC_Bypass_P32__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define ADC_Bypass_P32__PS CYREG_PRT3_PS
#define ADC_Bypass_P32__SHIFT 2
#define ADC_Bypass_P32__SLW CYREG_PRT3_SLW

/* ADC_Ext_CP_Clk */
#define ADC_Ext_CP_Clk__CFG0 CYREG_CLKDIST_DCFG1_CFG0
#define ADC_Ext_CP_Clk__CFG1 CYREG_CLKDIST_DCFG1_CFG1
#define ADC_Ext_CP_Clk__CFG2 CYREG_CLKDIST_DCFG1_CFG2
#define ADC_Ext_CP_Clk__CFG2_SRC_SEL_MASK 0x07u
#define ADC_Ext_CP_Clk__INDEX 0x01u
#define ADC_Ext_CP_Clk__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define ADC_Ext_CP_Clk__PM_ACT_MSK 0x02u
#define ADC_Ext_CP_Clk__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define ADC_Ext_CP_Clk__PM_STBY_MSK 0x02u

/* ADC_Clock_Ext */
#define ADC_Clock_Ext__CFG0 CYREG_CLKDIST_DCFG0_CFG0
#define ADC_Clock_Ext__CFG1 CYREG_CLKDIST_DCFG0_CFG1
#define ADC_Clock_Ext__CFG2 CYREG_CLKDIST_DCFG0_CFG2
#define ADC_Clock_Ext__CFG2_SRC_SEL_MASK 0x07u
#define ADC_Clock_Ext__INDEX 0x00u
#define ADC_Clock_Ext__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define ADC_Clock_Ext__PM_ACT_MSK 0x01u
#define ADC_Clock_Ext__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define ADC_Clock_Ext__PM_STBY_MSK 0x01u

/* Divider_PWMHW */
#define Divider_PWMHW__CAP0 CYREG_TMR0_CAP0
#define Divider_PWMHW__CAP1 CYREG_TMR0_CAP1
#define Divider_PWMHW__CFG0 CYREG_TMR0_CFG0
#define Divider_PWMHW__CFG1 CYREG_TMR0_CFG1
#define Divider_PWMHW__CFG2 CYREG_TMR0_CFG2
#define Divider_PWMHW__CNT_CMP0 CYREG_TMR0_CNT_CMP0
#define Divider_PWMHW__CNT_CMP1 CYREG_TMR0_CNT_CMP1
#define Divider_PWMHW__PER0 CYREG_TMR0_PER0
#define Divider_PWMHW__PER1 CYREG_TMR0_PER1
#define Divider_PWMHW__PM_ACT_CFG CYREG_PM_ACT_CFG3
#define Divider_PWMHW__PM_ACT_MSK 0x01u
#define Divider_PWMHW__PM_STBY_CFG CYREG_PM_STBY_CFG3
#define Divider_PWMHW__PM_STBY_MSK 0x01u
#define Divider_PWMHW__RT0 CYREG_TMR0_RT0
#define Divider_PWMHW__RT1 CYREG_TMR0_RT1
#define Divider_PWMHW__SR0 CYREG_TMR0_SR0

/* IDrive_viDAC8 */
#define IDrive_viDAC8__CR0 CYREG_DAC3_CR0
#define IDrive_viDAC8__CR1 CYREG_DAC3_CR1
#define IDrive_viDAC8__D CYREG_DAC3_D
#define IDrive_viDAC8__PM_ACT_CFG CYREG_PM_ACT_CFG8
#define IDrive_viDAC8__PM_ACT_MSK 0x08u
#define IDrive_viDAC8__PM_STBY_CFG CYREG_PM_STBY_CFG8
#define IDrive_viDAC8__PM_STBY_MSK 0x08u
#define IDrive_viDAC8__STROBE CYREG_DAC3_STROBE
#define IDrive_viDAC8__SW0 CYREG_DAC3_SW0
#define IDrive_viDAC8__SW2 CYREG_DAC3_SW2
#define IDrive_viDAC8__SW3 CYREG_DAC3_SW3
#define IDrive_viDAC8__SW4 CYREG_DAC3_SW4
#define IDrive_viDAC8__TR CYREG_DAC3_TR
#define IDrive_viDAC8__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DAC3_M1
#define IDrive_viDAC8__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DAC3_M2
#define IDrive_viDAC8__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DAC3_M3
#define IDrive_viDAC8__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DAC3_M4
#define IDrive_viDAC8__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DAC3_M5
#define IDrive_viDAC8__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DAC3_M6
#define IDrive_viDAC8__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DAC3_M7
#define IDrive_viDAC8__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DAC3_M8
#define IDrive_viDAC8__TST CYREG_DAC3_TST

/* PWM_1_PWMUDB */
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_A0_REG CYREG_B1_UDB05_06_A0
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_A1_REG CYREG_B1_UDB05_06_A1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_D0_REG CYREG_B1_UDB05_06_D0
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_D1_REG CYREG_B1_UDB05_06_D1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_DP_AUX_CTL_REG CYREG_B1_UDB05_06_ACTL
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_F0_REG CYREG_B1_UDB05_06_F0
#define PWM_1_PWMUDB_sP8_pwmdp_u0__16BIT_F1_REG CYREG_B1_UDB05_06_F1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__A0_A1_REG CYREG_B1_UDB05_A0_A1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__A0_REG CYREG_B1_UDB05_A0
#define PWM_1_PWMUDB_sP8_pwmdp_u0__A1_REG CYREG_B1_UDB05_A1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__D0_D1_REG CYREG_B1_UDB05_D0_D1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__D0_REG CYREG_B1_UDB05_D0
#define PWM_1_PWMUDB_sP8_pwmdp_u0__D1_REG CYREG_B1_UDB05_D1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__DP_AUX_CTL_REG CYREG_B1_UDB05_ACTL
#define PWM_1_PWMUDB_sP8_pwmdp_u0__F0_F1_REG CYREG_B1_UDB05_F0_F1
#define PWM_1_PWMUDB_sP8_pwmdp_u0__F0_REG CYREG_B1_UDB05_F0
#define PWM_1_PWMUDB_sP8_pwmdp_u0__F1_REG CYREG_B1_UDB05_F1
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__0__MASK 0x01u
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__0__POS 0
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__16BIT_STATUS_AUX_CTL_REG CYREG_B1_UDB05_06_ACTL
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__16BIT_STATUS_REG CYREG_B1_UDB05_06_ST
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__2__MASK 0x04u
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__2__POS 2
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__3__MASK 0x08u
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__3__POS 3
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__5__MASK 0x20u
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__5__POS 5
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__MASK 0x2Du
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__MASK_REG CYREG_B1_UDB05_MSK
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__STATUS_AUX_CTL_REG CYREG_B1_UDB05_ACTL
#define PWM_1_PWMUDB_sSTSReg_rstSts_stsreg__STATUS_REG CYREG_B1_UDB05_ST

/* drive_range */
#define drive_range__0__MASK 0x20u
#define drive_range__0__PC CYREG_PRT3_PC5
#define drive_range__0__PORT 3u
#define drive_range__0__SHIFT 5
#define drive_range__AG CYREG_PRT3_AG
#define drive_range__AMUX CYREG_PRT3_AMUX
#define drive_range__BIE CYREG_PRT3_BIE
#define drive_range__BIT_MASK CYREG_PRT3_BIT_MASK
#define drive_range__BYP CYREG_PRT3_BYP
#define drive_range__CTL CYREG_PRT3_CTL
#define drive_range__DM0 CYREG_PRT3_DM0
#define drive_range__DM1 CYREG_PRT3_DM1
#define drive_range__DM2 CYREG_PRT3_DM2
#define drive_range__DR CYREG_PRT3_DR
#define drive_range__INP_DIS CYREG_PRT3_INP_DIS
#define drive_range__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define drive_range__LCD_EN CYREG_PRT3_LCD_EN
#define drive_range__MASK 0x20u
#define drive_range__PORT 3u
#define drive_range__PRT CYREG_PRT3_PRT
#define drive_range__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define drive_range__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define drive_range__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define drive_range__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define drive_range__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define drive_range__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define drive_range__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define drive_range__PS CYREG_PRT3_PS
#define drive_range__SHIFT 5
#define drive_range__SLW CYREG_PRT3_SLW

/* Drive_Sense */
#define Drive_Sense__0__MASK 0x80u
#define Drive_Sense__0__PC CYREG_PRT3_PC7
#define Drive_Sense__0__PORT 3u
#define Drive_Sense__0__SHIFT 7
#define Drive_Sense__AG CYREG_PRT3_AG
#define Drive_Sense__AMUX CYREG_PRT3_AMUX
#define Drive_Sense__BIE CYREG_PRT3_BIE
#define Drive_Sense__BIT_MASK CYREG_PRT3_BIT_MASK
#define Drive_Sense__BYP CYREG_PRT3_BYP
#define Drive_Sense__CTL CYREG_PRT3_CTL
#define Drive_Sense__DM0 CYREG_PRT3_DM0
#define Drive_Sense__DM1 CYREG_PRT3_DM1
#define Drive_Sense__DM2 CYREG_PRT3_DM2
#define Drive_Sense__DR CYREG_PRT3_DR
#define Drive_Sense__INP_DIS CYREG_PRT3_INP_DIS
#define Drive_Sense__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Drive_Sense__LCD_EN CYREG_PRT3_LCD_EN
#define Drive_Sense__MASK 0x80u
#define Drive_Sense__PORT 3u
#define Drive_Sense__PRT CYREG_PRT3_PRT
#define Drive_Sense__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Drive_Sense__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Drive_Sense__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Drive_Sense__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Drive_Sense__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Drive_Sense__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Drive_Sense__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Drive_Sense__PS CYREG_PRT3_PS
#define Drive_Sense__SHIFT 7
#define Drive_Sense__SLW CYREG_PRT3_SLW

/* timer_clock */
#define timer_clock__CFG0 CYREG_CLKDIST_DCFG2_CFG0
#define timer_clock__CFG1 CYREG_CLKDIST_DCFG2_CFG1
#define timer_clock__CFG2 CYREG_CLKDIST_DCFG2_CFG2
#define timer_clock__CFG2_SRC_SEL_MASK 0x07u
#define timer_clock__INDEX 0x02u
#define timer_clock__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define timer_clock__PM_ACT_MSK 0x04u
#define timer_clock__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define timer_clock__PM_STBY_MSK 0x04u

/* Drive_ABuf */
#define Drive_ABuf__CR CYREG_OPAMP1_CR
#define Drive_ABuf__MX CYREG_OPAMP1_MX
#define Drive_ABuf__NPUMP_OPAMP_TR0 CYREG_NPUMP_OPAMP_TR0
#define Drive_ABuf__PM_ACT_CFG CYREG_PM_ACT_CFG4
#define Drive_ABuf__PM_ACT_MSK 0x02u
#define Drive_ABuf__PM_STBY_CFG CYREG_PM_STBY_CFG4
#define Drive_ABuf__PM_STBY_MSK 0x02u
#define Drive_ABuf__RSVD CYREG_OPAMP1_RSVD
#define Drive_ABuf__SW CYREG_OPAMP1_SW
#define Drive_ABuf__TR0 CYREG_OPAMP1_TR0
#define Drive_ABuf__TR1 CYREG_OPAMP1_TR1

/* Status_Reg */
#define Status_Reg_sts_sts_reg__0__MASK 0x01u
#define Status_Reg_sts_sts_reg__0__POS 0
#define Status_Reg_sts_sts_reg__16BIT_STATUS_AUX_CTL_REG CYREG_B1_UDB04_05_ACTL
#define Status_Reg_sts_sts_reg__16BIT_STATUS_REG CYREG_B1_UDB04_05_ST
#define Status_Reg_sts_sts_reg__MASK 0x01u
#define Status_Reg_sts_sts_reg__MASK_REG CYREG_B1_UDB04_MSK
#define Status_Reg_sts_sts_reg__MASK_ST_AUX_CTL_REG CYREG_B1_UDB04_MSK_ACTL
#define Status_Reg_sts_sts_reg__PER_ST_AUX_CTL_REG CYREG_B1_UDB04_MSK_ACTL
#define Status_Reg_sts_sts_reg__STATUS_AUX_CTL_REG CYREG_B1_UDB04_ACTL
#define Status_Reg_sts_sts_reg__STATUS_CNT_REG CYREG_B1_UDB04_ST_CTL
#define Status_Reg_sts_sts_reg__STATUS_CONTROL_REG CYREG_B1_UDB04_ST_CTL
#define Status_Reg_sts_sts_reg__STATUS_REG CYREG_B1_UDB04_ST

/* TIA_Output */
#define TIA_Output__0__MASK 0x02u
#define TIA_Output__0__PC CYREG_PRT0_PC1
#define TIA_Output__0__PORT 0u
#define TIA_Output__0__SHIFT 1
#define TIA_Output__AG CYREG_PRT0_AG
#define TIA_Output__AMUX CYREG_PRT0_AMUX
#define TIA_Output__BIE CYREG_PRT0_BIE
#define TIA_Output__BIT_MASK CYREG_PRT0_BIT_MASK
#define TIA_Output__BYP CYREG_PRT0_BYP
#define TIA_Output__CTL CYREG_PRT0_CTL
#define TIA_Output__DM0 CYREG_PRT0_DM0
#define TIA_Output__DM1 CYREG_PRT0_DM1
#define TIA_Output__DM2 CYREG_PRT0_DM2
#define TIA_Output__DR CYREG_PRT0_DR
#define TIA_Output__INP_DIS CYREG_PRT0_INP_DIS
#define TIA_Output__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define TIA_Output__LCD_EN CYREG_PRT0_LCD_EN
#define TIA_Output__MASK 0x02u
#define TIA_Output__PORT 0u
#define TIA_Output__PRT CYREG_PRT0_PRT
#define TIA_Output__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define TIA_Output__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define TIA_Output__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define TIA_Output__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define TIA_Output__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define TIA_Output__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define TIA_Output__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define TIA_Output__PS CYREG_PRT0_PS
#define TIA_Output__SHIFT 1
#define TIA_Output__SLW CYREG_PRT0_SLW

/* Drive_Out */
#define Drive_Out__0__MASK 0x40u
#define Drive_Out__0__PC CYREG_PRT3_PC6
#define Drive_Out__0__PORT 3u
#define Drive_Out__0__SHIFT 6
#define Drive_Out__AG CYREG_PRT3_AG
#define Drive_Out__AMUX CYREG_PRT3_AMUX
#define Drive_Out__BIE CYREG_PRT3_BIE
#define Drive_Out__BIT_MASK CYREG_PRT3_BIT_MASK
#define Drive_Out__BYP CYREG_PRT3_BYP
#define Drive_Out__CTL CYREG_PRT3_CTL
#define Drive_Out__DM0 CYREG_PRT3_DM0
#define Drive_Out__DM1 CYREG_PRT3_DM1
#define Drive_Out__DM2 CYREG_PRT3_DM2
#define Drive_Out__DR CYREG_PRT3_DR
#define Drive_Out__INP_DIS CYREG_PRT3_INP_DIS
#define Drive_Out__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Drive_Out__LCD_EN CYREG_PRT3_LCD_EN
#define Drive_Out__MASK 0x40u
#define Drive_Out__PORT 3u
#define Drive_Out__PRT CYREG_PRT3_PRT
#define Drive_Out__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Drive_Out__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Drive_Out__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Drive_Out__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Drive_Out__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Drive_Out__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Drive_Out__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Drive_Out__PS CYREG_PRT3_PS
#define Drive_Out__SHIFT 6
#define Drive_Out__SLW CYREG_PRT3_SLW

/* TIA_Input */
#define TIA_Input__0__MASK 0x08u
#define TIA_Input__0__PC CYREG_PRT0_PC3
#define TIA_Input__0__PORT 0u
#define TIA_Input__0__SHIFT 3
#define TIA_Input__AG CYREG_PRT0_AG
#define TIA_Input__AMUX CYREG_PRT0_AMUX
#define TIA_Input__BIE CYREG_PRT0_BIE
#define TIA_Input__BIT_MASK CYREG_PRT0_BIT_MASK
#define TIA_Input__BYP CYREG_PRT0_BYP
#define TIA_Input__CTL CYREG_PRT0_CTL
#define TIA_Input__DM0 CYREG_PRT0_DM0
#define TIA_Input__DM1 CYREG_PRT0_DM1
#define TIA_Input__DM2 CYREG_PRT0_DM2
#define TIA_Input__DR CYREG_PRT0_DR
#define TIA_Input__INP_DIS CYREG_PRT0_INP_DIS
#define TIA_Input__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define TIA_Input__LCD_EN CYREG_PRT0_LCD_EN
#define TIA_Input__MASK 0x08u
#define TIA_Input__PORT 0u
#define TIA_Input__PRT CYREG_PRT0_PRT
#define TIA_Input__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define TIA_Input__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define TIA_Input__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define TIA_Input__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define TIA_Input__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define TIA_Input__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define TIA_Input__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define TIA_Input__PS CYREG_PRT0_PS
#define TIA_Input__SHIFT 3
#define TIA_Input__SLW CYREG_PRT0_SLW

/* tia_range */
#define tia_range__0__MASK 0x02u
#define tia_range__0__PC CYREG_PRT4_PC1
#define tia_range__0__PORT 4u
#define tia_range__0__SHIFT 1
#define tia_range__AG CYREG_PRT4_AG
#define tia_range__AMUX CYREG_PRT4_AMUX
#define tia_range__BIE CYREG_PRT4_BIE
#define tia_range__BIT_MASK CYREG_PRT4_BIT_MASK
#define tia_range__BYP CYREG_PRT4_BYP
#define tia_range__CTL CYREG_PRT4_CTL
#define tia_range__DM0 CYREG_PRT4_DM0
#define tia_range__DM1 CYREG_PRT4_DM1
#define tia_range__DM2 CYREG_PRT4_DM2
#define tia_range__DR CYREG_PRT4_DR
#define tia_range__INP_DIS CYREG_PRT4_INP_DIS
#define tia_range__LCD_COM_SEG CYREG_PRT4_LCD_COM_SEG
#define tia_range__LCD_EN CYREG_PRT4_LCD_EN
#define tia_range__MASK 0x02u
#define tia_range__PORT 4u
#define tia_range__PRT CYREG_PRT4_PRT
#define tia_range__PRTDSI__CAPS_SEL CYREG_PRT4_CAPS_SEL
#define tia_range__PRTDSI__DBL_SYNC_IN CYREG_PRT4_DBL_SYNC_IN
#define tia_range__PRTDSI__OE_SEL0 CYREG_PRT4_OE_SEL0
#define tia_range__PRTDSI__OE_SEL1 CYREG_PRT4_OE_SEL1
#define tia_range__PRTDSI__OUT_SEL0 CYREG_PRT4_OUT_SEL0
#define tia_range__PRTDSI__OUT_SEL1 CYREG_PRT4_OUT_SEL1
#define tia_range__PRTDSI__SYNC_OUT CYREG_PRT4_SYNC_OUT
#define tia_range__PS CYREG_PRT4_PS
#define tia_range__SHIFT 1
#define tia_range__SLW CYREG_PRT4_SLW

/* TIA_Sense */
#define TIA_Sense__0__MASK 0x20u
#define TIA_Sense__0__PC CYREG_PRT0_PC5
#define TIA_Sense__0__PORT 0u
#define TIA_Sense__0__SHIFT 5
#define TIA_Sense__AG CYREG_PRT0_AG
#define TIA_Sense__AMUX CYREG_PRT0_AMUX
#define TIA_Sense__BIE CYREG_PRT0_BIE
#define TIA_Sense__BIT_MASK CYREG_PRT0_BIT_MASK
#define TIA_Sense__BYP CYREG_PRT0_BYP
#define TIA_Sense__CTL CYREG_PRT0_CTL
#define TIA_Sense__DM0 CYREG_PRT0_DM0
#define TIA_Sense__DM1 CYREG_PRT0_DM1
#define TIA_Sense__DM2 CYREG_PRT0_DM2
#define TIA_Sense__DR CYREG_PRT0_DR
#define TIA_Sense__INP_DIS CYREG_PRT0_INP_DIS
#define TIA_Sense__LCD_COM_SEG CYREG_PRT0_LCD_COM_SEG
#define TIA_Sense__LCD_EN CYREG_PRT0_LCD_EN
#define TIA_Sense__MASK 0x20u
#define TIA_Sense__PORT 0u
#define TIA_Sense__PRT CYREG_PRT0_PRT
#define TIA_Sense__PRTDSI__CAPS_SEL CYREG_PRT0_CAPS_SEL
#define TIA_Sense__PRTDSI__DBL_SYNC_IN CYREG_PRT0_DBL_SYNC_IN
#define TIA_Sense__PRTDSI__OE_SEL0 CYREG_PRT0_OE_SEL0
#define TIA_Sense__PRTDSI__OE_SEL1 CYREG_PRT0_OE_SEL1
#define TIA_Sense__PRTDSI__OUT_SEL0 CYREG_PRT0_OUT_SEL0
#define TIA_Sense__PRTDSI__OUT_SEL1 CYREG_PRT0_OUT_SEL1
#define TIA_Sense__PRTDSI__SYNC_OUT CYREG_PRT0_SYNC_OUT
#define TIA_Sense__PS CYREG_PRT0_PS
#define TIA_Sense__SHIFT 5
#define TIA_Sense__SLW CYREG_PRT0_SLW

/* ADC_DSM4 */
#define ADC_DSM4__BUF0 CYREG_DSM0_BUF0
#define ADC_DSM4__BUF1 CYREG_DSM0_BUF1
#define ADC_DSM4__BUF2 CYREG_DSM0_BUF2
#define ADC_DSM4__BUF3 CYREG_DSM0_BUF3
#define ADC_DSM4__CLK CYREG_DSM0_CLK
#define ADC_DSM4__CR0 CYREG_DSM0_CR0
#define ADC_DSM4__CR1 CYREG_DSM0_CR1
#define ADC_DSM4__CR10 CYREG_DSM0_CR10
#define ADC_DSM4__CR11 CYREG_DSM0_CR11
#define ADC_DSM4__CR12 CYREG_DSM0_CR12
#define ADC_DSM4__CR13 CYREG_DSM0_CR13
#define ADC_DSM4__CR14 CYREG_DSM0_CR14
#define ADC_DSM4__CR15 CYREG_DSM0_CR15
#define ADC_DSM4__CR16 CYREG_DSM0_CR16
#define ADC_DSM4__CR17 CYREG_DSM0_CR17
#define ADC_DSM4__CR2 CYREG_DSM0_CR2
#define ADC_DSM4__CR3 CYREG_DSM0_CR3
#define ADC_DSM4__CR4 CYREG_DSM0_CR4
#define ADC_DSM4__CR5 CYREG_DSM0_CR5
#define ADC_DSM4__CR6 CYREG_DSM0_CR6
#define ADC_DSM4__CR7 CYREG_DSM0_CR7
#define ADC_DSM4__CR8 CYREG_DSM0_CR8
#define ADC_DSM4__CR9 CYREG_DSM0_CR9
#define ADC_DSM4__DEM0 CYREG_DSM0_DEM0
#define ADC_DSM4__DEM1 CYREG_DSM0_DEM1
#define ADC_DSM4__MISC CYREG_DSM0_MISC
#define ADC_DSM4__OUT0 CYREG_DSM0_OUT0
#define ADC_DSM4__OUT1 CYREG_DSM0_OUT1
#define ADC_DSM4__REF0 CYREG_DSM0_REF0
#define ADC_DSM4__REF1 CYREG_DSM0_REF1
#define ADC_DSM4__REF2 CYREG_DSM0_REF2
#define ADC_DSM4__REF3 CYREG_DSM0_REF3
#define ADC_DSM4__RSVD1 CYREG_DSM0_RSVD1
#define ADC_DSM4__SW0 CYREG_DSM0_SW0
#define ADC_DSM4__SW2 CYREG_DSM0_SW2
#define ADC_DSM4__SW3 CYREG_DSM0_SW3
#define ADC_DSM4__SW4 CYREG_DSM0_SW4
#define ADC_DSM4__SW6 CYREG_DSM0_SW6
#define ADC_DSM4__TR0 CYREG_NPUMP_DSM_TR0
#define ADC_DSM4__TST0 CYREG_DSM0_TST0
#define ADC_DSM4__TST1 CYREG_DSM0_TST1

/* Drive_In */
#define Drive_In__0__MASK 0x10u
#define Drive_In__0__PC CYREG_PRT3_PC4
#define Drive_In__0__PORT 3u
#define Drive_In__0__SHIFT 4
#define Drive_In__AG CYREG_PRT3_AG
#define Drive_In__AMUX CYREG_PRT3_AMUX
#define Drive_In__BIE CYREG_PRT3_BIE
#define Drive_In__BIT_MASK CYREG_PRT3_BIT_MASK
#define Drive_In__BYP CYREG_PRT3_BYP
#define Drive_In__CTL CYREG_PRT3_CTL
#define Drive_In__DM0 CYREG_PRT3_DM0
#define Drive_In__DM1 CYREG_PRT3_DM1
#define Drive_In__DM2 CYREG_PRT3_DM2
#define Drive_In__DR CYREG_PRT3_DR
#define Drive_In__INP_DIS CYREG_PRT3_INP_DIS
#define Drive_In__LCD_COM_SEG CYREG_PRT3_LCD_COM_SEG
#define Drive_In__LCD_EN CYREG_PRT3_LCD_EN
#define Drive_In__MASK 0x10u
#define Drive_In__PORT 3u
#define Drive_In__PRT CYREG_PRT3_PRT
#define Drive_In__PRTDSI__CAPS_SEL CYREG_PRT3_CAPS_SEL
#define Drive_In__PRTDSI__DBL_SYNC_IN CYREG_PRT3_DBL_SYNC_IN
#define Drive_In__PRTDSI__OE_SEL0 CYREG_PRT3_OE_SEL0
#define Drive_In__PRTDSI__OE_SEL1 CYREG_PRT3_OE_SEL1
#define Drive_In__PRTDSI__OUT_SEL0 CYREG_PRT3_OUT_SEL0
#define Drive_In__PRTDSI__OUT_SEL1 CYREG_PRT3_OUT_SEL1
#define Drive_In__PRTDSI__SYNC_OUT CYREG_PRT3_SYNC_OUT
#define Drive_In__PS CYREG_PRT3_PS
#define Drive_In__SHIFT 4
#define Drive_In__SLW CYREG_PRT3_SLW

/* LCD_MOSI */
#define LCD_MOSI__0__MASK 0x10u
#define LCD_MOSI__0__PC CYREG_PRT2_PC4
#define LCD_MOSI__0__PORT 2u
#define LCD_MOSI__0__SHIFT 4
#define LCD_MOSI__AG CYREG_PRT2_AG
#define LCD_MOSI__AMUX CYREG_PRT2_AMUX
#define LCD_MOSI__BIE CYREG_PRT2_BIE
#define LCD_MOSI__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_MOSI__BYP CYREG_PRT2_BYP
#define LCD_MOSI__CTL CYREG_PRT2_CTL
#define LCD_MOSI__DM0 CYREG_PRT2_DM0
#define LCD_MOSI__DM1 CYREG_PRT2_DM1
#define LCD_MOSI__DM2 CYREG_PRT2_DM2
#define LCD_MOSI__DR CYREG_PRT2_DR
#define LCD_MOSI__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_MOSI__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_MOSI__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_MOSI__MASK 0x10u
#define LCD_MOSI__PORT 2u
#define LCD_MOSI__PRT CYREG_PRT2_PRT
#define LCD_MOSI__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_MOSI__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_MOSI__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_MOSI__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_MOSI__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_MOSI__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_MOSI__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_MOSI__PS CYREG_PRT2_PS
#define LCD_MOSI__SHIFT 4
#define LCD_MOSI__SLW CYREG_PRT2_SLW

/* LCD_SCLK */
#define LCD_SCLK__0__MASK 0x08u
#define LCD_SCLK__0__PC CYREG_PRT2_PC3
#define LCD_SCLK__0__PORT 2u
#define LCD_SCLK__0__SHIFT 3
#define LCD_SCLK__AG CYREG_PRT2_AG
#define LCD_SCLK__AMUX CYREG_PRT2_AMUX
#define LCD_SCLK__BIE CYREG_PRT2_BIE
#define LCD_SCLK__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_SCLK__BYP CYREG_PRT2_BYP
#define LCD_SCLK__CTL CYREG_PRT2_CTL
#define LCD_SCLK__DM0 CYREG_PRT2_DM0
#define LCD_SCLK__DM1 CYREG_PRT2_DM1
#define LCD_SCLK__DM2 CYREG_PRT2_DM2
#define LCD_SCLK__DR CYREG_PRT2_DR
#define LCD_SCLK__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_SCLK__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_SCLK__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_SCLK__MASK 0x08u
#define LCD_SCLK__PORT 2u
#define LCD_SCLK__PRT CYREG_PRT2_PRT
#define LCD_SCLK__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_SCLK__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_SCLK__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_SCLK__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_SCLK__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_SCLK__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_SCLK__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_SCLK__PS CYREG_PRT2_PS
#define LCD_SCLK__SHIFT 3
#define LCD_SCLK__SLW CYREG_PRT2_SLW

/* Power_SW */
#define Power_SW__0__MASK 0x80u
#define Power_SW__0__PC CYREG_PRT5_PC7
#define Power_SW__0__PORT 5u
#define Power_SW__0__SHIFT 7
#define Power_SW__AG CYREG_PRT5_AG
#define Power_SW__AMUX CYREG_PRT5_AMUX
#define Power_SW__BIE CYREG_PRT5_BIE
#define Power_SW__BIT_MASK CYREG_PRT5_BIT_MASK
#define Power_SW__BYP CYREG_PRT5_BYP
#define Power_SW__CTL CYREG_PRT5_CTL
#define Power_SW__DM0 CYREG_PRT5_DM0
#define Power_SW__DM1 CYREG_PRT5_DM1
#define Power_SW__DM2 CYREG_PRT5_DM2
#define Power_SW__DR CYREG_PRT5_DR
#define Power_SW__INP_DIS CYREG_PRT5_INP_DIS
#define Power_SW__LCD_COM_SEG CYREG_PRT5_LCD_COM_SEG
#define Power_SW__LCD_EN CYREG_PRT5_LCD_EN
#define Power_SW__MASK 0x80u
#define Power_SW__PORT 5u
#define Power_SW__PRT CYREG_PRT5_PRT
#define Power_SW__PRTDSI__CAPS_SEL CYREG_PRT5_CAPS_SEL
#define Power_SW__PRTDSI__DBL_SYNC_IN CYREG_PRT5_DBL_SYNC_IN
#define Power_SW__PRTDSI__OE_SEL0 CYREG_PRT5_OE_SEL0
#define Power_SW__PRTDSI__OE_SEL1 CYREG_PRT5_OE_SEL1
#define Power_SW__PRTDSI__OUT_SEL0 CYREG_PRT5_OUT_SEL0
#define Power_SW__PRTDSI__OUT_SEL1 CYREG_PRT5_OUT_SEL1
#define Power_SW__PRTDSI__SYNC_OUT CYREG_PRT5_SYNC_OUT
#define Power_SW__PS CYREG_PRT5_PS
#define Power_SW__SHIFT 7
#define Power_SW__SLW CYREG_PRT5_SLW

/* Sine_DMA */
#define Sine_DMA__DRQ_CTL CYREG_IDMUX_DRQ_CTL0
#define Sine_DMA__DRQ_NUMBER 0u
#define Sine_DMA__NUMBEROF_TDS 0u
#define Sine_DMA__PRIORITY 2u
#define Sine_DMA__TERMIN_EN 0u
#define Sine_DMA__TERMIN_SEL 0u
#define Sine_DMA__TERMOUT0_EN 1u
#define Sine_DMA__TERMOUT0_SEL 0u
#define Sine_DMA__TERMOUT1_EN 0u
#define Sine_DMA__TERMOUT1_SEL 0u

/* TIA_ABuf */
#define TIA_ABuf__CR CYREG_OPAMP0_CR
#define TIA_ABuf__MX CYREG_OPAMP0_MX
#define TIA_ABuf__NPUMP_OPAMP_TR0 CYREG_NPUMP_OPAMP_TR0
#define TIA_ABuf__PM_ACT_CFG CYREG_PM_ACT_CFG4
#define TIA_ABuf__PM_ACT_MSK 0x01u
#define TIA_ABuf__PM_STBY_CFG CYREG_PM_STBY_CFG4
#define TIA_ABuf__PM_STBY_MSK 0x01u
#define TIA_ABuf__RSVD CYREG_OPAMP0_RSVD
#define TIA_ABuf__SW CYREG_OPAMP0_SW
#define TIA_ABuf__TR0 CYREG_OPAMP0_TR0
#define TIA_ABuf__TR1 CYREG_OPAMP0_TR1

/* ADC_DEC */
#define ADC_DEC__COHER CYREG_DEC_COHER
#define ADC_DEC__CR CYREG_DEC_CR
#define ADC_DEC__DR1 CYREG_DEC_DR1
#define ADC_DEC__DR2 CYREG_DEC_DR2
#define ADC_DEC__DR2H CYREG_DEC_DR2H
#define ADC_DEC__GCOR CYREG_DEC_GCOR
#define ADC_DEC__GCORH CYREG_DEC_GCORH
#define ADC_DEC__GVAL CYREG_DEC_GVAL
#define ADC_DEC__OCOR CYREG_DEC_OCOR
#define ADC_DEC__OCORH CYREG_DEC_OCORH
#define ADC_DEC__OCORM CYREG_DEC_OCORM
#define ADC_DEC__OUTSAMP CYREG_DEC_OUTSAMP
#define ADC_DEC__OUTSAMPH CYREG_DEC_OUTSAMPH
#define ADC_DEC__OUTSAMPM CYREG_DEC_OUTSAMPM
#define ADC_DEC__OUTSAMPS CYREG_DEC_OUTSAMPS
#define ADC_DEC__PM_ACT_CFG CYREG_PM_ACT_CFG10
#define ADC_DEC__PM_ACT_MSK 0x01u
#define ADC_DEC__PM_STBY_CFG CYREG_PM_STBY_CFG10
#define ADC_DEC__PM_STBY_MSK 0x01u
#define ADC_DEC__SHIFT1 CYREG_DEC_SHIFT1
#define ADC_DEC__SHIFT2 CYREG_DEC_SHIFT2
#define ADC_DEC__SR CYREG_DEC_SR
#define ADC_DEC__TRIM__M1 CYREG_FLSHID_CUST_TABLES_DEC_M1
#define ADC_DEC__TRIM__M2 CYREG_FLSHID_CUST_TABLES_DEC_M2
#define ADC_DEC__TRIM__M3 CYREG_FLSHID_CUST_TABLES_DEC_M3
#define ADC_DEC__TRIM__M4 CYREG_FLSHID_CUST_TABLES_DEC_M4
#define ADC_DEC__TRIM__M5 CYREG_FLSHID_CUST_TABLES_DEC_M5
#define ADC_DEC__TRIM__M6 CYREG_FLSHID_CUST_TABLES_DEC_M6
#define ADC_DEC__TRIM__M7 CYREG_FLSHID_CUST_TABLES_DEC_M7
#define ADC_DEC__TRIM__M8 CYREG_FLSHID_CUST_TABLES_DEC_M8

/* ADC_IRQ */
#define ADC_IRQ__INTC_CLR_EN_REG CYREG_NVIC_CLRENA0
#define ADC_IRQ__INTC_CLR_PD_REG CYREG_NVIC_CLRPEND0
#define ADC_IRQ__INTC_MASK 0x20000000u
#define ADC_IRQ__INTC_NUMBER 29u
#define ADC_IRQ__INTC_PRIOR_NUM 7u
#define ADC_IRQ__INTC_PRIOR_REG CYREG_NVIC_PRI_29
#define ADC_IRQ__INTC_SET_EN_REG CYREG_NVIC_SETENA0
#define ADC_IRQ__INTC_SET_PD_REG CYREG_NVIC_SETPEND0

/* Clock_5 */
#define Clock_5__CFG0 CYREG_CLKDIST_DCFG4_CFG0
#define Clock_5__CFG1 CYREG_CLKDIST_DCFG4_CFG1
#define Clock_5__CFG2 CYREG_CLKDIST_DCFG4_CFG2
#define Clock_5__CFG2_SRC_SEL_MASK 0x07u
#define Clock_5__INDEX 0x04u
#define Clock_5__PM_ACT_CFG CYREG_PM_ACT_CFG2
#define Clock_5__PM_ACT_MSK 0x10u
#define Clock_5__PM_STBY_CFG CYREG_PM_STBY_CFG2
#define Clock_5__PM_STBY_MSK 0x10u

/* LCD_D_C */
#define LCD_D_C__0__MASK 0x04u
#define LCD_D_C__0__PC CYREG_PRT2_PC2
#define LCD_D_C__0__PORT 2u
#define LCD_D_C__0__SHIFT 2
#define LCD_D_C__AG CYREG_PRT2_AG
#define LCD_D_C__AMUX CYREG_PRT2_AMUX
#define LCD_D_C__BIE CYREG_PRT2_BIE
#define LCD_D_C__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_D_C__BYP CYREG_PRT2_BYP
#define LCD_D_C__CTL CYREG_PRT2_CTL
#define LCD_D_C__DM0 CYREG_PRT2_DM0
#define LCD_D_C__DM1 CYREG_PRT2_DM1
#define LCD_D_C__DM2 CYREG_PRT2_DM2
#define LCD_D_C__DR CYREG_PRT2_DR
#define LCD_D_C__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_D_C__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_D_C__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_D_C__MASK 0x04u
#define LCD_D_C__PORT 2u
#define LCD_D_C__PRT CYREG_PRT2_PRT
#define LCD_D_C__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_D_C__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_D_C__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_D_C__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_D_C__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_D_C__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_D_C__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_D_C__PS CYREG_PRT2_PS
#define LCD_D_C__SHIFT 2
#define LCD_D_C__SLW CYREG_PRT2_SLW

/* LCD_RST */
#define LCD_RST__0__MASK 0x02u
#define LCD_RST__0__PC CYREG_PRT2_PC1
#define LCD_RST__0__PORT 2u
#define LCD_RST__0__SHIFT 1
#define LCD_RST__AG CYREG_PRT2_AG
#define LCD_RST__AMUX CYREG_PRT2_AMUX
#define LCD_RST__BIE CYREG_PRT2_BIE
#define LCD_RST__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_RST__BYP CYREG_PRT2_BYP
#define LCD_RST__CTL CYREG_PRT2_CTL
#define LCD_RST__DM0 CYREG_PRT2_DM0
#define LCD_RST__DM1 CYREG_PRT2_DM1
#define LCD_RST__DM2 CYREG_PRT2_DM2
#define LCD_RST__DR CYREG_PRT2_DR
#define LCD_RST__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_RST__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_RST__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_RST__MASK 0x02u
#define LCD_RST__PORT 2u
#define LCD_RST__PRT CYREG_PRT2_PRT
#define LCD_RST__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_RST__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_RST__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_RST__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_RST__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_RST__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_RST__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_RST__PS CYREG_PRT2_PS
#define LCD_RST__SHIFT 1
#define LCD_RST__SLW CYREG_PRT2_SLW

/* LCD_CS */
#define LCD_CS__0__MASK 0x01u
#define LCD_CS__0__PC CYREG_PRT2_PC0
#define LCD_CS__0__PORT 2u
#define LCD_CS__0__SHIFT 0
#define LCD_CS__AG CYREG_PRT2_AG
#define LCD_CS__AMUX CYREG_PRT2_AMUX
#define LCD_CS__BIE CYREG_PRT2_BIE
#define LCD_CS__BIT_MASK CYREG_PRT2_BIT_MASK
#define LCD_CS__BYP CYREG_PRT2_BYP
#define LCD_CS__CTL CYREG_PRT2_CTL
#define LCD_CS__DM0 CYREG_PRT2_DM0
#define LCD_CS__DM1 CYREG_PRT2_DM1
#define LCD_CS__DM2 CYREG_PRT2_DM2
#define LCD_CS__DR CYREG_PRT2_DR
#define LCD_CS__INP_DIS CYREG_PRT2_INP_DIS
#define LCD_CS__LCD_COM_SEG CYREG_PRT2_LCD_COM_SEG
#define LCD_CS__LCD_EN CYREG_PRT2_LCD_EN
#define LCD_CS__MASK 0x01u
#define LCD_CS__PORT 2u
#define LCD_CS__PRT CYREG_PRT2_PRT
#define LCD_CS__PRTDSI__CAPS_SEL CYREG_PRT2_CAPS_SEL
#define LCD_CS__PRTDSI__DBL_SYNC_IN CYREG_PRT2_DBL_SYNC_IN
#define LCD_CS__PRTDSI__OE_SEL0 CYREG_PRT2_OE_SEL0
#define LCD_CS__PRTDSI__OE_SEL1 CYREG_PRT2_OE_SEL1
#define LCD_CS__PRTDSI__OUT_SEL0 CYREG_PRT2_OUT_SEL0
#define LCD_CS__PRTDSI__OUT_SEL1 CYREG_PRT2_OUT_SEL1
#define LCD_CS__PRTDSI__SYNC_OUT CYREG_PRT2_SYNC_OUT
#define LCD_CS__PS CYREG_PRT2_PS
#define LCD_CS__SHIFT 0
#define LCD_CS__SLW CYREG_PRT2_SLW

/* LED_BL */
#define LED_BL__0__MASK 0x40u
#define LED_BL__0__PC CYREG_PRT1_PC6
#define LED_BL__0__PORT 1u
#define LED_BL__0__SHIFT 6
#define LED_BL__AG CYREG_PRT1_AG
#define LED_BL__AMUX CYREG_PRT1_AMUX
#define LED_BL__BIE CYREG_PRT1_BIE
#define LED_BL__BIT_MASK CYREG_PRT1_BIT_MASK
#define LED_BL__BYP CYREG_PRT1_BYP
#define LED_BL__CTL CYREG_PRT1_CTL
#define LED_BL__DM0 CYREG_PRT1_DM0
#define LED_BL__DM1 CYREG_PRT1_DM1
#define LED_BL__DM2 CYREG_PRT1_DM2
#define LED_BL__DR CYREG_PRT1_DR
#define LED_BL__INP_DIS CYREG_PRT1_INP_DIS
#define LED_BL__LCD_COM_SEG CYREG_PRT1_LCD_COM_SEG
#define LED_BL__LCD_EN CYREG_PRT1_LCD_EN
#define LED_BL__MASK 0x40u
#define LED_BL__PORT 1u
#define LED_BL__PRT CYREG_PRT1_PRT
#define LED_BL__PRTDSI__CAPS_SEL CYREG_PRT1_CAPS_SEL
#define LED_BL__PRTDSI__DBL_SYNC_IN CYREG_PRT1_DBL_SYNC_IN
#define LED_BL__PRTDSI__OE_SEL0 CYREG_PRT1_OE_SEL0
#define LED_BL__PRTDSI__OE_SEL1 CYREG_PRT1_OE_SEL1
#define LED_BL__PRTDSI__OUT_SEL0 CYREG_PRT1_OUT_SEL0
#define LED_BL__PRTDSI__OUT_SEL1 CYREG_PRT1_OUT_SEL1
#define LED_BL__PRTDSI__SYNC_OUT CYREG_PRT1_SYNC_OUT
#define LED_BL__PS CYREG_PRT1_PS
#define LED_BL__SHIFT 6
#define LED_BL__SLW CYREG_PRT1_SLW

/* SOC_Go */
#define SOC_Go_Sync_ctrl_reg__0__MASK 0x01u
#define SOC_Go_Sync_ctrl_reg__0__POS 0
#define SOC_Go_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B0_UDB05_06_ACTL
#define SOC_Go_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B0_UDB05_06_CTL
#define SOC_Go_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B0_UDB05_06_CTL
#define SOC_Go_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B0_UDB05_06_CTL
#define SOC_Go_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B0_UDB05_06_CTL
#define SOC_Go_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B0_UDB05_06_MSK
#define SOC_Go_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B0_UDB05_06_MSK
#define SOC_Go_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B0_UDB05_06_MSK
#define SOC_Go_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B0_UDB05_06_MSK
#define SOC_Go_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B0_UDB05_ACTL
#define SOC_Go_Sync_ctrl_reg__CONTROL_REG CYREG_B0_UDB05_CTL
#define SOC_Go_Sync_ctrl_reg__CONTROL_ST_REG CYREG_B0_UDB05_ST_CTL
#define SOC_Go_Sync_ctrl_reg__COUNT_REG CYREG_B0_UDB05_CTL
#define SOC_Go_Sync_ctrl_reg__COUNT_ST_REG CYREG_B0_UDB05_ST_CTL
#define SOC_Go_Sync_ctrl_reg__MASK 0x01u
#define SOC_Go_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B0_UDB05_MSK_ACTL
#define SOC_Go_Sync_ctrl_reg__PERIOD_REG CYREG_B0_UDB05_MSK
#define SOC_Go_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B0_UDB05_MSK_ACTL

/* Phase */
#define Phase_Sync_ctrl_reg__0__MASK 0x01u
#define Phase_Sync_ctrl_reg__0__POS 0
#define Phase_Sync_ctrl_reg__16BIT_CONTROL_AUX_CTL_REG CYREG_B1_UDB04_05_ACTL
#define Phase_Sync_ctrl_reg__16BIT_CONTROL_CONTROL_REG CYREG_B1_UDB04_05_CTL
#define Phase_Sync_ctrl_reg__16BIT_CONTROL_COUNT_REG CYREG_B1_UDB04_05_CTL
#define Phase_Sync_ctrl_reg__16BIT_COUNT_CONTROL_REG CYREG_B1_UDB04_05_CTL
#define Phase_Sync_ctrl_reg__16BIT_COUNT_COUNT_REG CYREG_B1_UDB04_05_CTL
#define Phase_Sync_ctrl_reg__16BIT_MASK_MASK_REG CYREG_B1_UDB04_05_MSK
#define Phase_Sync_ctrl_reg__16BIT_MASK_PERIOD_REG CYREG_B1_UDB04_05_MSK
#define Phase_Sync_ctrl_reg__16BIT_PERIOD_MASK_REG CYREG_B1_UDB04_05_MSK
#define Phase_Sync_ctrl_reg__16BIT_PERIOD_PERIOD_REG CYREG_B1_UDB04_05_MSK
#define Phase_Sync_ctrl_reg__CONTROL_AUX_CTL_REG CYREG_B1_UDB04_ACTL
#define Phase_Sync_ctrl_reg__CONTROL_REG CYREG_B1_UDB04_CTL
#define Phase_Sync_ctrl_reg__CONTROL_ST_REG CYREG_B1_UDB04_ST_CTL
#define Phase_Sync_ctrl_reg__COUNT_REG CYREG_B1_UDB04_CTL
#define Phase_Sync_ctrl_reg__COUNT_ST_REG CYREG_B1_UDB04_ST_CTL
#define Phase_Sync_ctrl_reg__MASK 0x01u
#define Phase_Sync_ctrl_reg__MASK_CTL_AUX_CTL_REG CYREG_B1_UDB04_MSK_ACTL
#define Phase_Sync_ctrl_reg__PERIOD_REG CYREG_B1_UDB04_MSK
#define Phase_Sync_ctrl_reg__PER_CTL_AUX_CTL_REG CYREG_B1_UDB04_MSK_ACTL

/* Miscellaneous */
/* -- WARNING: define names containing LEOPARD or PANTHER are deprecated and will be removed in a future release */
#define CYDEV_DEBUGGING_DPS_SWD_SWV 6
#define CYDEV_CONFIG_UNUSED_IO_AllowButWarn 0
#define CYDEV_CONFIGURATION_MODE_COMPRESSED 0
#define CYDEV_CONFIG_FASTBOOT_ENABLED 1
#define CYDEV_CHIP_REV_PSOC5LP_PRODUCTION 0u
#define CYDEV_CHIP_REVISION_5B_PRODUCTION 0u
#define CYDEV_CHIP_MEMBER_5B 4u
#define CYDEV_CHIP_FAMILY_PSOC5 3u
#define CYDEV_CHIP_DIE_PSOC5LP 4u
#define CYDEV_CHIP_DIE_EXPECT CYDEV_CHIP_DIE_PSOC5LP
#define BCLK__BUS_CLK__HZ 16000000U
#define BCLK__BUS_CLK__KHZ 16000U
#define BCLK__BUS_CLK__MHZ 16U
#define CYDEV_CHIP_DIE_ACTUAL CYDEV_CHIP_DIE_EXPECT
#define CYDEV_CHIP_DIE_LEOPARD 1u
#define CYDEV_CHIP_DIE_PANTHER 3u
#define CYDEV_CHIP_DIE_PSOC4A 2u
#define CYDEV_CHIP_DIE_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_PSOC3 1u
#define CYDEV_CHIP_FAMILY_PSOC4 2u
#define CYDEV_CHIP_FAMILY_UNKNOWN 0u
#define CYDEV_CHIP_FAMILY_USED CYDEV_CHIP_FAMILY_PSOC5
#define CYDEV_CHIP_JTAG_ID 0x2E120069u
#define CYDEV_CHIP_MEMBER_3A 1u
#define CYDEV_CHIP_MEMBER_4A 2u
#define CYDEV_CHIP_MEMBER_5A 3u
#define CYDEV_CHIP_MEMBER_UNKNOWN 0u
#define CYDEV_CHIP_MEMBER_USED CYDEV_CHIP_MEMBER_5B
#define CYDEV_CHIP_REVISION_3A_ES1 0u
#define CYDEV_CHIP_REVISION_3A_ES2 1u
#define CYDEV_CHIP_REVISION_3A_ES3 3u
#define CYDEV_CHIP_REVISION_3A_PRODUCTION 3u
#define CYDEV_CHIP_REVISION_4A_ES0 17u
#define CYDEV_CHIP_REVISION_4A_PRODUCTION 17u
#define CYDEV_CHIP_REVISION_5A_ES0 0u
#define CYDEV_CHIP_REVISION_5A_ES1 1u
#define CYDEV_CHIP_REVISION_5A_PRODUCTION 1u
#define CYDEV_CHIP_REVISION_5B_ES0 0u
#define CYDEV_CHIP_REVISION_USED CYDEV_CHIP_REVISION_5B_PRODUCTION
#define CYDEV_CHIP_REV_EXPECT CYDEV_CHIP_REV_PSOC5LP_PRODUCTION
#define CYDEV_CHIP_REV_LEOPARD_ES1 0u
#define CYDEV_CHIP_REV_LEOPARD_ES2 1u
#define CYDEV_CHIP_REV_LEOPARD_ES3 3u
#define CYDEV_CHIP_REV_LEOPARD_PRODUCTION 3u
#define CYDEV_CHIP_REV_PANTHER_ES0 0u
#define CYDEV_CHIP_REV_PANTHER_ES1 1u
#define CYDEV_CHIP_REV_PANTHER_PRODUCTION 1u
#define CYDEV_CHIP_REV_PSOC4A_ES0 17u
#define CYDEV_CHIP_REV_PSOC4A_PRODUCTION 17u
#define CYDEV_CHIP_REV_PSOC5LP_ES0 0u
#define CYDEV_CONFIGURATION_COMPRESSED 1
#define CYDEV_CONFIGURATION_DMA 0
#define CYDEV_CONFIGURATION_ECC 0
#define CYDEV_CONFIGURATION_IMOENABLED CYDEV_CONFIG_FASTBOOT_ENABLED
#define CYDEV_CONFIGURATION_MODE CYDEV_CONFIGURATION_MODE_COMPRESSED
#define CYDEV_CONFIGURATION_MODE_DMA 2
#define CYDEV_CONFIGURATION_MODE_UNCOMPRESSED 1
#define CYDEV_CONFIG_UNUSED_IO CYDEV_CONFIG_UNUSED_IO_AllowButWarn
#define CYDEV_CONFIG_UNUSED_IO_AllowWithInfo 1
#define CYDEV_CONFIG_UNUSED_IO_Disallowed 2
#define CYDEV_DEBUGGING_DPS CYDEV_DEBUGGING_DPS_SWD_SWV
#define CYDEV_DEBUGGING_DPS_Disable 3
#define CYDEV_DEBUGGING_DPS_JTAG_4 1
#define CYDEV_DEBUGGING_DPS_JTAG_5 0
#define CYDEV_DEBUGGING_DPS_SWD 2
#define CYDEV_DEBUGGING_ENABLE 1
#define CYDEV_DEBUGGING_REQXRES 1
#define CYDEV_DEBUGGING_XRES 0
#define CYDEV_DEBUG_ENABLE_MASK 0x20u
#define CYDEV_DEBUG_ENABLE_REGISTER CYREG_MLOGIC_DEBUG
#define CYDEV_DMA_CHANNELS_AVAILABLE 24u
#define CYDEV_ECC_ENABLE 0
#define CYDEV_HEAP_SIZE 0x1000
#define CYDEV_INSTRUCT_CACHE_ENABLED 0
#define CYDEV_INTR_RISING 0x00000001u
#define CYDEV_PROJ_TYPE 0
#define CYDEV_PROJ_TYPE_BOOTLOADER 1
#define CYDEV_PROJ_TYPE_LOADABLE 2
#define CYDEV_PROJ_TYPE_MULTIAPPBOOTLOADER 3
#define CYDEV_PROJ_TYPE_STANDARD 0
#define CYDEV_PROTECTION_ENABLE 0
#define CYDEV_STACK_SIZE 0x4000
#define CYDEV_USE_BUNDLED_CMSIS 1
#define CYDEV_VARIABLE_VDDA 0
#define CYDEV_VDDA 5
#define CYDEV_VDDA_MV 5000
#define CYDEV_VDDD 5
#define CYDEV_VDDD_MV 5000
#define CYDEV_VDDIO0 5
#define CYDEV_VDDIO0_MV 5000
#define CYDEV_VDDIO1 5
#define CYDEV_VDDIO1_MV 5000
#define CYDEV_VDDIO2 5
#define CYDEV_VDDIO2_MV 5000
#define CYDEV_VDDIO3 5
#define CYDEV_VDDIO3_MV 5000
#define CYDEV_VIO0 5
#define CYDEV_VIO0_MV 5000
#define CYDEV_VIO1 5
#define CYDEV_VIO1_MV 5000
#define CYDEV_VIO2 5
#define CYDEV_VIO2_MV 5000
#define CYDEV_VIO3 5
#define CYDEV_VIO3_MV 5000
#define DMA_CHANNELS_USED__MASK0 0x00000001u
#define CYDEV_BOOTLOADER_ENABLE 0

#endif /* INCLUDED_CYFITTER_H */
