/*******************************************************************************
* FILENAME: cyfitter_cfg.h
* PSoC Creator 2.2 Service Pack 1
*
* Description:
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright 2012, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef CYFITTER_CFG_H
#define CYFITTER_CFG_H

#include <cytypes.h>

extern void cyfitter_cfg(void);

/* Analog Set/Unset methods */
extern void SetAnalogRoutingPumps(uint8 enabled);
extern void Measure_Mux_Set(uint8 channel);
extern void Measure_Mux_Unset(uint8 channel);
/* Measure_Mux__addrTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern uint8 CYXDATA * const CYCODE Measure_Mux__addrTable[4];
/* Measure_Mux__maskTable is an implementation detail of the AMux.
   Code that depends on it may be incompatible with other versions
   of PSoC Creator. */
extern const uint8 CYCODE Measure_Mux__maskTable[4];
extern void ResistiveTouch_1_AMux_DisconnectAll(void);
extern void ResistiveTouch_1_AMux_Next(void);
extern int8 ResistiveTouch_1_AMux_curChannel;


#endif /* CYFITTER_CFG_H */

/*[]*/
