/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.2 Service Pack 1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <Drive_Sense_aliases.h>
#include <Drive_Sense.h>
#include <IDrive.h>
#include <Measure_Mux.h>
#include <TIA_Output_aliases.h>
#include <TIA_Output.h>
#include <TIA.h>
#include <Clipping_Sense.h>
#include <TIA_Input_aliases.h>
#include <TIA_Input.h>
#include <Drive_Out_aliases.h>
#include <Drive_Out.h>
#include <Status_Reg.h>
#include <Phase.h>
#include <Drive.h>
#include <Drive_In_aliases.h>
#include <Drive_In.h>
#include <Divider.h>
#include <Sine_DMA_dma.h>
#include <TIA_Sense_aliases.h>
#include <TIA_Sense.h>
#include <SOC_Go.h>
#include <LCD_SCLK_aliases.h>
#include <LCD_SCLK.h>
#include <LCD_D_C_aliases.h>
#include <LCD_D_C.h>
#include <ADC_Clock_Ext.h>
#include <drive_range_aliases.h>
#include <drive_range.h>
#include <LCD_RST_aliases.h>
#include <LCD_RST.h>
#include <ADC.h>
#include <drive_freq_range_aliases.h>
#include <drive_freq_range.h>
#include <tia_range_aliases.h>
#include <tia_range.h>
#include <LCD_CS_aliases.h>
#include <LCD_CS.h>
#include <LCD_MOSI_aliases.h>
#include <LCD_MOSI.h>
#include <LCD_LCD.h>
#include <LCD_glcdfont.h>
#include <ResistiveTouch_1.h>
#include <Power_SW_aliases.h>
#include <Power_SW.h>
#include <LED_BL_aliases.h>
#include <LED_BL.h>
#include <Clock_5.h>
#include <timer_clock.h>
#include <PWM_1.h>
#include <BoostConv.h>
#include <ADC_Bypass_P32_aliases.h>
#include <ADC_Bypass_P32.h>
#include <ADC_Ext_CP_Clk.h>
#include <LCD_LCD_Control.h>
#include <LCD_LCD_SPI.h>
#include <LCD_LCD_SPI_PVT.h>
#include <ResistiveTouch_1_AMux.h>
#include <ResistiveTouch_1_xm_aliases.h>
#include <ResistiveTouch_1_xm.h>
#include <ResistiveTouch_1_xp_aliases.h>
#include <ResistiveTouch_1_xp.h>
#include <ResistiveTouch_1_ym_aliases.h>
#include <ResistiveTouch_1_ym.h>
#include <ResistiveTouch_1_yp_aliases.h>
#include <ResistiveTouch_1_yp.h>
#include <ResistiveTouch_1_ADC_SAR.h>
#include <LCD_LCD_SPI_IntClock.h>
#include <ResistiveTouch_1_ADC_SAR_IRQ.h>
#include <ResistiveTouch_1_ADC_SAR_theACLK.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>

/*[]*/

